[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  # The default is 'esbuild' for Node 18+ on Netlify, 
  # but you can explicitly set it if you prefer:
  # node_bundler = "esbuild"

# Optionally, you can configure more function settings here, 
# such as specifying which Node version you’d like to use, 
# environment variables, etc.
